### ISSUE TITLE
Issue with code in Wiki (and tutorial)

### ISSUE THREAD

**Issue by zentuit** [remedyhealth/content-pull#44]
```    
constructor() {
        this._puller = super(
            'space-id',
            'api-key'
        );
    }
```
This will throw an error `ReferenceError: this is not defined`

Looking that up, I found this: https://mitchellsimoens.com/this-is-undefined-what/

Seems you can't use `this` before calling `super` in the constructor

I think the constructor only needs to be:
```
constructor() {
    super(
        'space-id',
        'api-key'
    );
}
```

**Comment by mrsteele** [comment]
This was resolved from a pending pull request.

https://github.com/remedyhealth/content-pull/commit/64d9f6827913573d2ec4cd501406b36f990cef94

...However the wiki was not resolved, so thank you for the reminder.

This has now been resolved. Glad to see you and I think alike!
